blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ DÃºvidas gerais
    url: https://github.com/DevPool1/TP-ADC-SITE/discussions
    about: Usa as discussions para perguntas ou esclarecimentos.
